### ISSUE TITLE
Where can I download papers

### ISSUE THREAD

**Issue by maozhiqiang** [FhGSpCo/FhGSpCo.github.io#2]
hi @FhGSpCo ！
      Where can I download papers， thanks!

**Comment by FhGSpCo** [comment]
Hi,
The preprint will be uploaded to arxiv shortly.

**Comment by maozhiqiang** [comment]
@FhGSpCo thanks!

**Comment by FhGSpCo** [comment]
Here you are: https://arxiv.org/abs/2011.01557

**Comment by maozhiqiang** [comment]
@FhGSpCo thanks!
